export const HomeObjOne = {
    id: 'about',
    toScroll: 'signup',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'One stop',
    headLine: 'Seamless from your content to sales',
    description: 'Bring your tutorial content to the e-market in easy way.',
    moreDes: '',
    buttonLabel: 'Get started',
    imgStart: false,
    img: require('../../../images/svg-1.svg').default,
    alt: 'Social Media',
    dark: true,
    primary: true,
    darkText: false,
}
export const HomeObjTwo = {
    id: 'discover',
    toScroll: '',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'Your knowledge is asset',
    headLine: 'Expand your content to sales',
    description: 'Our platform aims to connect your audience from Social Media channels to exploring available for purchase e-learning content and merchandise. Enabling this provides e-commerce features for the online education industry.',
    moreDes: ['Individual content creators that would like to expand their revenue by connecting their audience to an extended course and sell related goods to the same viewers.', ' Small businesses - online bootcamps that periodically run cohorts and provide interactive learning. '],
    buttonLabel: 'Learn more',
    imgStart: true,
    img: require('../../../images/svg-2.svg').default,
    alt: 'Discover',
    dark: false,
    primary: false,
    darkText: true,
}
export const HomeObjThree = {
    id: 'signup',
    toScroll: '',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'Join our community',
    headLine: 'Creating account is extremely easy',
    description: 'Get everything setup and ready in under 2 minutes. All you need to do is add your infomation and you\'re ready to go.',
    moreDes: '',
    buttonLabel: 'Start Now',
    imgStart: false,
    img: require('../../../images/svg-3.svg').default,
    alt: 'Sign up',
    dark: false,
    primary: false,
    darkText: true,
}