export const HomeObjOne = {
    id: 'about',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Premium Bank',
    headLine: 'Ultimated Transaction with zero fee',
    description: 'Get access our exclusive app to allow you to send unlimited transactions without getting charging any fees.',
    buttonLabel: 'Get started',
    imgStart: false,
    img: require('../../images/svg-1.svg').default,
    alt: 'Social Media',
    dark: true,
    primary: true,
    darkText: false,
}
export const HomeObjTwo = {
    id: 'discover',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'Unlimited Access',
    headLine: 'Login to your account any time',
    description: 'We have you covered no matter where you located. All you need in an Internet connection and a computer.',
    buttonLabel: 'Learn more',
    imgStart: true,
    img: require('../../images/svg-2.svg').default,
    alt: 'Discover',
    dark: false,
    primary: false,
    darkText: true,
}
export const HomeObjThree = {
    id: 'signup',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'Join our Team',
    headLine: 'Creating account is extremely easy',
    description: 'Get everything setup and ready in under 10 minutes. All you need to do is add your infomation and you\'re ready to go.',
    buttonLabel: 'Start Now',
    imgStart: false,
    img: require('../../images/svg-3.svg').default,
    alt: 'Sign up',
    dark: false,
    primary: false,
    darkText: true,
}